!ifndef CUSTOM_TARGETS
CUSTOM_TARGETS=_EMPTY_TARGET_
!endif

all: another

depend: another-depend

clean generated realclean $(CUSTOM_TARGETS):
	$(MAKE) -$(MAKEFLAGS) -f Makefile.another.bmak $(@)

another:
	$(MAKE) -$(MAKEFLAGS) -f Makefile.another.bmak all

another-depend:
	$(MAKE) -$(MAKEFLAGS) -f Makefile.another.bmak depend

project_name_list:
	@echo another
