#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
CFG = Win32 Debug

ifeq ($(CFG), Win32 Debug)
CC            = 
CXX           = 
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -I"crapday" -I".."
OBJEXT        = 
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.dll
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = .exe
LIBPREFIX     = 
LIBSUFFIX     = d
GENFLAGS      = 
LDLIBS        = 
OBJS          = foo$(OBJEXT)
AREXT         = .lib
LIB           = $(LTARGETDIR)$(LIBPREFIX)dll$(LIBSUFFIX)$(AREXT)
SOEXT         = .dll
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)dll$(LIBSUFFIX)$(SOEXT)
SRC           = foo.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = $(DYNAMICFLAGS)
endif
ifeq ($(CFG), Win32 Release)
CC            = 
CXX           = 
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -I"crapday" -I".."
OBJEXT        = 
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.dll
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = .exe
LIBPREFIX     = 
LIBSUFFIX     = 
GENFLAGS      = 
LDLIBS        = 
OBJS          = foo$(OBJEXT)
AREXT         = .lib
LIB           = $(LTARGETDIR)$(LIBPREFIX)dll$(LIBSUFFIX)$(AREXT)
SOEXT         = .dll
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)dll$(LIBSUFFIX)$(SOEXT)
SRC           = foo.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = $(DYNAMICFLAGS)
endif

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(SHLIB)

$(SHLIB): $(OBJS)
	@$(TESTDIRSTART) "$(SHTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(SHTARGETDIR)"
	$(LINK.cc) $(SHFLAGS) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

$(LIB): $(OBJS)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	$(AR) $(ARFLAGS) $(LIB) $(OBJS)

generated: $(GENERATED_DIRTY)
	@-:

foo$(OBJEXT): foo.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) foo.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(SHLIB) $(LIB)

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) $(CHK_SOURCES)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------

$(DEPENDENCIES):
	@$(TOUCH) $(DEPENDENCIES)

depend:
	-$(MPC_ROOT)/depgen.pl  $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

ifeq ($(CFG), x64 Debug)
CC            = 
CXX           = 
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -I"crapday" -I".."
OBJEXT        = 
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.dll
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = .exe
LIBPREFIX     = 
LIBSUFFIX     = d
GENFLAGS      = 
LDLIBS        = 
OBJS          = foo$(OBJEXT)
AREXT         = .lib
LIB           = $(LTARGETDIR)$(LIBPREFIX)dll$(LIBSUFFIX)$(AREXT)
SOEXT         = .dll
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)dll$(LIBSUFFIX)$(SOEXT)
SRC           = foo.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = $(DYNAMICFLAGS)
endif
ifeq ($(CFG), x64 Release)
CC            = 
CXX           = 
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -I"crapday" -I".."
OBJEXT        = 
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.dll
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = .exe
LIBPREFIX     = 
LIBSUFFIX     = 
GENFLAGS      = 
LDLIBS        = 
OBJS          = foo$(OBJEXT)
AREXT         = .lib
LIB           = $(LTARGETDIR)$(LIBPREFIX)dll$(LIBSUFFIX)$(AREXT)
SOEXT         = .dll
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)dll$(LIBSUFFIX)$(SOEXT)
SRC           = foo.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = $(DYNAMICFLAGS)
endif

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(SHLIB)

$(SHLIB): $(OBJS)
	@$(TESTDIRSTART) "$(SHTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(SHTARGETDIR)"
	$(LINK.cc) $(SHFLAGS) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

$(LIB): $(OBJS)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	$(AR) $(ARFLAGS) $(LIB) $(OBJS)

generated: $(GENERATED_DIRTY)
	@-:

foo$(OBJEXT): foo.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) foo.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(SHLIB) $(LIB)

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) $(CHK_SOURCES)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------

$(DEPENDENCIES):
	@$(TOUCH) $(DEPENDENCIES)

depend:
	-$(MPC_ROOT)/depgen.pl  $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

# DO NOT DELETE THIS LINE
