#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------

TARGETDIR       = ./
TARGET          = $(TARGETDIR)aly.dll
LDFLAGS         = -lib:.
CFLAGS          =
TESTDIRSTART    = test -d
TESTDIREND      = ||
RM              = rm -rf
MKDIR           = mkdir -p

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(GENERATED_DIRTY) $(TARGET)

$(TARGET): aly.cs
	@$(TESTDIRSTART) "$(TARGETDIR)" $(TESTDIREND) $(MKDIR) "$(TARGETDIR)"
	mcs -target:library -out:$(TARGET) $(CFLAGS) $(LDFLAGS) aly.cs

generated: $(GENERATED_DIRTY)
	@-:

clean:
	-$(RM) $(TARGET)

realclean: clean

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------

depend:
	@-:
