#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------

TARGETDIR       = ./
TARGET          = $(TARGETDIR)cras.dll
LDFLAGS         = -lib:.
CFLAGS          =
TESTDIRSTART    = test -d
TESTDIREND      = ||
CAT             = cat
MV              = mv -f
RM              = rm -rf
CP              = cp -p
NUL             = /dev/null
MKDIR           = mkdir -p

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(GENERATED_DIRTY) $(TARGET)

$(TARGET): cras.cs
	@$(TESTDIRSTART) "$(TARGETDIR)" $(TESTDIREND) $(MKDIR) "$(TARGETDIR)"
	gmcs -target:library -out:$(TARGET) $(CFLAGS) $(LDFLAGS) cras.cs

bundle:

generated: $(GENERATED_DIRTY)
	@-:

clean:
	-$(RM) $(TARGET)

realclean: clean

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------

depend:
	@-:
